# Generated by Django 5.0.1 on 2024-03-17 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('is_boss', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Protsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protsent', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
