# Generated by Django 5.0.1 on 2024-02-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Protsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protsent', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
