# Generated by Django 5.0.1 on 2024-02-06 09:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Maishiy_texnika', [('SubCat1', 'SubCat1'), ('SubCat2', 'SubCat2')]), ('Noutbooklar', [('SubCat3', 'SubCat3'), ('SubCat4', 'SubCat4')]), ('Smartfonlar', [('SubCat5', 'SubCat5'), ('SubCat6', 'SubCat6')])], max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('prosent', models.FloatField(blank=True, null=True)),
                ('postavshik', models.CharField(max_length=2000, null=True)),
                ('tasdiq', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.admin')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_key', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='RecPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='rec_pro')),
                ('is_rec', models.BooleanField(default=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Rus', 'Rus'), ('Uzbek', 'Uzbek')], max_length=20)),
                ('name', models.CharField(max_length=250, null=True)),
                ('about', models.TextField(null=True)),
                ('description', models.TextField()),
                ('model', models.CharField(max_length=250, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.subcategory')),
            ],
        ),
    ]
