# Generated by Django 5.0.1 on 2024-03-17 05:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        ('Partner', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Maishiy_texnika', 'Maishiy_texnika'), ('Noutbooklar', 'Noutbooklar'), ('Smartfonlar', 'Smartfonlar'), ('Aksesuarlar', 'Aksesuarlar'), ('Maishiy_texnika', 'Maishiy_texnika'), ('Texnika', 'Texnika'), ('Atir', 'Atir'), ('kitob', 'kitob'), ('Avtobar', 'Avtobar')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RecPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='rec_pro')),
                ('is_rec', models.BooleanField(default=True)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Smartfonlar', [('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Honor', 'Honor'), ('Xiaomi', 'Xiaomi'), ('Vivo', 'Vivo'), ('Realme', 'Realme'), ('Huawei', 'Huawei'), ('OPPO', 'OPPO'), ('Tecno', 'Tecno'), ('Planshetlar', 'Planshetlar'), ('boshqa', 'boshqa')]), ('Noutbooklar', [('Macbook', 'Macbook'), ('HP', 'HP'), ('Lenova', 'Lenova'), ('Acer', 'Acer'), ('Samsung', 'Samsung'), ('Dell', 'Dell'), ('MSI', 'MSI'), ('Asus', 'Asus'), ('boshqa', 'boshqa')]), ('Aksesuarlar', [('Microfon', 'Microfon'), ('Klaviatura', 'Klaviatura'), ('Sumka', 'Sumka'), ('Sichqoncha', 'Sichqoncha'), ('Printer', 'Printer'), ('Quloqchin', 'Quloqchin'), ('boshqa', 'boshqa')]), ('Maishiy_texnika', [('Changyutgich', 'Changyutgich'), ('Kuller', 'Kuller'), ('Dazmol', 'Dazmol'), ('Televizor', 'Televizor'), ('Muzlatgich', 'Muzlatgich'), ('Kir yuvish mashinasi', 'Kir yuvish mashinasi'), ('konditsioner', 'konditsioner'), ('Gaz plita', 'Gaz plita'), ('boshqa', 'boshqa')]), ('Atir', [('Ayol', 'Ayol'), ('Erkak', 'Erkak')]), ('kitob', [('Diniy', 'Diniy'), ('Badiiy', 'Badiiy')]), ('Autobar', [('Autobar', 'Autobar')])], max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(null=True)),
                ('cost', models.FloatField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('postavshik', models.CharField(max_length=2000, null=True)),
                ('tasdiq', models.BooleanField(default=False)),
                ('cre_cost', models.JSONField(blank=True, null=True)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.admin')),
                ('partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Partner.partner')),
                ('protsent', models.ManyToManyField(to='Admin.protsent')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('buyurtma_berish', 'buyurtma_berish'), ('buyurtma_tayyorlanmoqda', 'buyurtma_tayyorlanmoqda'), ('yetkazib_berish_jarayoni', 'yetkazib_berish_jarayoni'), ('yetkazilgan', 'yetkazilgan'), ('bekor_qilingan', 'bekor_qilingan')], default='buyurtma_berish', max_length=200)),
                ('payment', models.CharField(choices=[('naqt', 'naqt'), ('card', 'card'), ('credit', 'credit')], default='naqt', max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=10, null=True)),
                ('pro_x', models.CharField(choices=[('is_buy', 'is_buy'), ('is_like', 'is_like')], max_length=50, null=True)),
                ('oy', models.IntegerField()),
                ('phone_cre', models.CharField(max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamini +998XXXXXXXXX kabi kiriting!', regex='d{0,9}')])),
                ('tasdiq', models.BooleanField(null=True)),
                ('color', models.CharField(max_length=120, null=True)),
                ('cost_order', models.FloatField(blank=True, null=True)),
                ('name_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.protsent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.users')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color_key', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('Rus', 'Rus'), ('Uzbek', 'Uzbek')], max_length=20)),
                ('name', models.CharField(max_length=250, null=True)),
                ('about', models.TextField(null=True)),
                ('description', models.TextField()),
                ('model', models.CharField(max_length=250, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.subcategory')),
            ],
        ),
    ]
