# Generated by Django 5.0.1 on 2024-02-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Maishiy_texnika', 'Maishiy_texnika'), ('Noutbooklar', 'Noutbooklar'), ('Smartfonlar', 'Smartfonlar'), ('Planshetlar', 'Planshetlar'), ('Aksesuarlar', 'Aksesuarlar'), ('Maishiy_texnika', 'Maishiy_texnika'), ('Texnika', 'Texnika'), ('Atir', 'Atir'), ('kitob', 'kitob'), ('Avtobar', 'Avtobar')], max_length=100)),
            ],
        ),
    ]
