# Generated by Django 5.0.1 on 2024-02-12 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_protsent'),
        ('Product', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('costs', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='prosent',
        ),
        migrations.RemoveField(
            model_name='recpro',
            name='product',
        ),
        migrations.AddField(
            model_name='product',
            name='protsent',
            field=models.ManyToManyField(to='Admin.protsent'),
        ),
        migrations.AddField(
            model_name='recpro',
            name='about',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='recpro',
            name='name',
            field=models.CharField(default=2, max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('Maishiy_texnika', 'Maishiy_texnika'), ('Noutbooklar', 'Noutbooklar'), ('Smartfonlar', 'Smartfonlar'), ('Aksesuarlar', 'Aksesuarlar'), ('Maishiy_texnika', 'Maishiy_texnika'), ('Texnika', 'Texnika'), ('Atir', 'Atir'), ('kitob', 'kitob'), ('Avtobar', 'Avtobar')], max_length=100),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.CharField(choices=[('Smartfonlar', [('Apple', 'Apple'), ('Samsung', 'Samsung'), ('Honor', 'Honor'), ('Xiaomi', 'Xiaomi'), ('Vivo', 'Vivo'), ('Realme', 'Realme'), ('Huawei', 'Huawei'), ('OPPO', 'OPPO'), ('Tecno', 'Tecno'), ('Planshetlar', 'Planshetlar'), ('boshqa', 'boshqa')]), ('Noutbooklar', [('Macbook', 'Macbook'), ('HP', 'HP'), ('Lenova', 'Lenova'), ('Acer', 'Acer'), ('Samsung', 'Samsung'), ('Dell', 'Dell'), ('MSI', 'MSI'), ('Asus', 'Asus'), ('boshqa', 'boshqa')]), ('Aksesuarlar', [('Microfon', 'Microfon'), ('Klaviatura', 'Klaviatura'), ('Sumka', 'Sumka'), ('Sichqoncha', 'Sichqoncha'), ('Printer', 'Printer'), ('Quloqchin', 'Quloqchin'), ('boshqa', 'boshqa')]), ('Maishiy_texnika', [('Changyutgich', 'Changyutgich'), ('Kuller', 'Kuller'), ('Dazmol', 'Dazmol'), ('Televizor', 'Televizor'), ('Muzlatgich', 'Muzlatgich'), ('Kir yuvish mashinasi', 'Kir yuvish mashinasi'), ('konditsioner', 'konditsioner'), ('Gaz plita', 'Gaz plita'), ('boshqa', 'boshqa')]), ('Atir', [('Ayol', 'Ayol'), ('Erkak', 'Erkak')]), ('kitob', [('Diniy', 'Diniy'), ('Badiiy', 'Badiiy')]), ('Autobar', [('Autobar', 'Autobar')])], max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='cre_cost',
            field=models.ManyToManyField(to='Product.costs'),
        ),
    ]
