# Generated by Django 5.0.1 on 2024-02-12 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0003_costs_remove_product_prosent_remove_recpro_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cre_cost',
            field=models.ManyToManyField(null=True, to='Product.costs'),
        ),
    ]
