# Generated by Django 5.0.1 on 2024-02-19 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0005_alter_product_cre_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cre_cost',
            field=models.ManyToManyField(null=True, to='Product.costs'),
        ),
    ]
