# Generated by Django 5.0.1 on 2024-03-10 02:30

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_admin_is_boss_admin_password_admin_username'),
        ('Partner', '0001_initial'),
        ('Product', '0005_alter_product_cre_cost'),
        ('User', '0002_user_password'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cre_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Partner.partner'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now=True)),
                ('state', models.CharField(choices=[('buyurtma_berish', 'buyurtma_berish'), ('buyurtma_tayyorlanmoqda', 'buyurtma_tayyorlanmoqda'), ('yetkazib_berish_jarayoni', 'yetkazib_berish_jarayoni'), ('yetkazilgan', 'yetkazilgan'), ('bekor_qilingan', 'bekor_qilingan')], default='buyurtma_berish', max_length=200)),
                ('payment', models.CharField(choices=[('naqt', 'naqt'), ('card', 'card'), ('credit', 'credit')], default='naqt', max_length=100)),
                ('quantity', models.IntegerField(null=True)),
                ('rate', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], default=1, max_length=10, null=True)),
                ('pro_x', models.CharField(choices=[('is_buy', 'is_buy'), ('is_like', 'is_like')], max_length=50, null=True)),
                ('oy', models.IntegerField()),
                ('phone_cre', models.CharField(max_length=9, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Telefon raqamini +998XXXXXXXXX kabi kiriting!', regex='d{0,9}')])),
                ('tasdiq', models.BooleanField(null=True)),
                ('color', models.CharField(max_length=120, null=True)),
                ('cost_order', models.FloatField(blank=True, null=True)),
                ('name_credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.protsent')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='Product.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.user')),
            ],
        ),
        migrations.DeleteModel(
            name='Costs',
        ),
        migrations.AddField(
            model_name='product',
            name='cre_cost',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
