# Generated by Django 5.0.1 on 2024-02-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0007_alter_product_cre_cost'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cre_cost',
        ),
        migrations.AddField(
            model_name='product',
            name='cre_cost',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
