# Generated by Django 5.0.1 on 2024-02-20 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_remove_product_cre_cost_product_cre_cost'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Costs',
        ),
    ]
