# Generated by Django 5.0.1 on 2024-02-12 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default=1, max_length=8),
            preserve_default=False,
        ),
    ]
